import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { exec } from 'child_process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

function copyFiles() {
  return new Promise((resolve, reject) => {
    exec('npm run copy', (error, stdout, stderr) => {
      if (error) {
        console.error(`Error copying files: ${error}`);
        reject(error);
        return;
      }
      console.log('✅ Files copied to Obsidian plugin directory');
      resolve(stdout);
    });
  });
}

const plugin = {
  name: 'copy-on-rebuild',
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length === 0) {
        try {
          await copyFiles();
        } catch (error) {
          console.error('❌ Failed to copy files after rebuild');
        }
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  sourcesContent: true,
  sourceRoot: '.',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [plugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  console.log('🔍 Starting watch build with source maps...');
  console.log('👀 Watching for changes...');

  // Start watching with the plugin
  await context.watch();
  console.log(
    '✅ Watch mode active - files will be copied automatically on changes',
  );
}
